//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/InputActions/MainInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainInputActions"",
    ""maps"": [
        {
            ""name"": ""Mouse"",
            ""id"": ""5b6fc92f-e0c7-4232-bffe-690df94849dc"",
            ""actions"": [
                {
                    ""name"": ""LeftButtonClick"",
                    ""type"": ""Button"",
                    ""id"": ""1c1f642e-9a6f-4479-8c52-6851f920ff51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightButtonClick"",
                    ""type"": ""Button"",
                    ""id"": ""4478ad80-2a27-49dd-940e-2eeeb56d07cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7bb67b8a-a472-41c9-b495-56c13b8832bf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""LeftButtonClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7667a6a2-3620-428f-81ad-89183ec99ad4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RightButtonClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Shortcut"",
            ""id"": ""58ed7e8b-2dd1-463b-9af2-516a6ee319a7"",
            ""actions"": [
                {
                    ""name"": ""Ctrl+LeftMouse"",
                    ""type"": ""Button"",
                    ""id"": ""60c34102-6dfb-4b47-b7c3-f5d1de1bc12b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""3f646dd7-61f8-459f-a39a-a48754e42840"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ctrl+LeftMouse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f68110af-0595-4867-8b4d-9997da526929"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ctrl+LeftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""16074707-6b7b-4ac3-9fdc-238de95ff774"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ctrl+LeftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""id"": ""1edf01dc-ecd8-42dd-8223-d9c5a3ace60d"",
            ""actions"": [
                {
                    ""name"": ""Ctrl"",
                    ""type"": ""Button"",
                    ""id"": ""859a030a-339a-4271-9b2f-0cd7ecf5b3a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""43bba0b1-8eb2-4c63-8ed1-7608f72cc441"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ctrl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Mouse
        m_Mouse = asset.FindActionMap("Mouse", throwIfNotFound: true);
        m_Mouse_LeftButtonClick = m_Mouse.FindAction("LeftButtonClick", throwIfNotFound: true);
        m_Mouse_RightButtonClick = m_Mouse.FindAction("RightButtonClick", throwIfNotFound: true);
        // Shortcut
        m_Shortcut = asset.FindActionMap("Shortcut", throwIfNotFound: true);
        m_Shortcut_CtrlLeftMouse = m_Shortcut.FindAction("Ctrl+LeftMouse", throwIfNotFound: true);
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_Ctrl = m_Keyboard.FindAction("Ctrl", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mouse
    private readonly InputActionMap m_Mouse;
    private List<IMouseActions> m_MouseActionsCallbackInterfaces = new List<IMouseActions>();
    private readonly InputAction m_Mouse_LeftButtonClick;
    private readonly InputAction m_Mouse_RightButtonClick;
    public struct MouseActions
    {
        private @MainInputActions m_Wrapper;
        public MouseActions(@MainInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftButtonClick => m_Wrapper.m_Mouse_LeftButtonClick;
        public InputAction @RightButtonClick => m_Wrapper.m_Mouse_RightButtonClick;
        public InputActionMap Get() { return m_Wrapper.m_Mouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseActions set) { return set.Get(); }
        public void AddCallbacks(IMouseActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseActionsCallbackInterfaces.Add(instance);
            @LeftButtonClick.started += instance.OnLeftButtonClick;
            @LeftButtonClick.performed += instance.OnLeftButtonClick;
            @LeftButtonClick.canceled += instance.OnLeftButtonClick;
            @RightButtonClick.started += instance.OnRightButtonClick;
            @RightButtonClick.performed += instance.OnRightButtonClick;
            @RightButtonClick.canceled += instance.OnRightButtonClick;
        }

        private void UnregisterCallbacks(IMouseActions instance)
        {
            @LeftButtonClick.started -= instance.OnLeftButtonClick;
            @LeftButtonClick.performed -= instance.OnLeftButtonClick;
            @LeftButtonClick.canceled -= instance.OnLeftButtonClick;
            @RightButtonClick.started -= instance.OnRightButtonClick;
            @RightButtonClick.performed -= instance.OnRightButtonClick;
            @RightButtonClick.canceled -= instance.OnRightButtonClick;
        }

        public void RemoveCallbacks(IMouseActions instance)
        {
            if (m_Wrapper.m_MouseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMouseActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MouseActions @Mouse => new MouseActions(this);

    // Shortcut
    private readonly InputActionMap m_Shortcut;
    private List<IShortcutActions> m_ShortcutActionsCallbackInterfaces = new List<IShortcutActions>();
    private readonly InputAction m_Shortcut_CtrlLeftMouse;
    public struct ShortcutActions
    {
        private @MainInputActions m_Wrapper;
        public ShortcutActions(@MainInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @CtrlLeftMouse => m_Wrapper.m_Shortcut_CtrlLeftMouse;
        public InputActionMap Get() { return m_Wrapper.m_Shortcut; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShortcutActions set) { return set.Get(); }
        public void AddCallbacks(IShortcutActions instance)
        {
            if (instance == null || m_Wrapper.m_ShortcutActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShortcutActionsCallbackInterfaces.Add(instance);
            @CtrlLeftMouse.started += instance.OnCtrlLeftMouse;
            @CtrlLeftMouse.performed += instance.OnCtrlLeftMouse;
            @CtrlLeftMouse.canceled += instance.OnCtrlLeftMouse;
        }

        private void UnregisterCallbacks(IShortcutActions instance)
        {
            @CtrlLeftMouse.started -= instance.OnCtrlLeftMouse;
            @CtrlLeftMouse.performed -= instance.OnCtrlLeftMouse;
            @CtrlLeftMouse.canceled -= instance.OnCtrlLeftMouse;
        }

        public void RemoveCallbacks(IShortcutActions instance)
        {
            if (m_Wrapper.m_ShortcutActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShortcutActions instance)
        {
            foreach (var item in m_Wrapper.m_ShortcutActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShortcutActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShortcutActions @Shortcut => new ShortcutActions(this);

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private List<IKeyboardActions> m_KeyboardActionsCallbackInterfaces = new List<IKeyboardActions>();
    private readonly InputAction m_Keyboard_Ctrl;
    public struct KeyboardActions
    {
        private @MainInputActions m_Wrapper;
        public KeyboardActions(@MainInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Ctrl => m_Wrapper.m_Keyboard_Ctrl;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Add(instance);
            @Ctrl.started += instance.OnCtrl;
            @Ctrl.performed += instance.OnCtrl;
            @Ctrl.canceled += instance.OnCtrl;
        }

        private void UnregisterCallbacks(IKeyboardActions instance)
        {
            @Ctrl.started -= instance.OnCtrl;
            @Ctrl.performed -= instance.OnCtrl;
            @Ctrl.canceled -= instance.OnCtrl;
        }

        public void RemoveCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);
    private int m_KeyboardandMouseSchemeIndex = -1;
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    public interface IMouseActions
    {
        void OnLeftButtonClick(InputAction.CallbackContext context);
        void OnRightButtonClick(InputAction.CallbackContext context);
    }
    public interface IShortcutActions
    {
        void OnCtrlLeftMouse(InputAction.CallbackContext context);
    }
    public interface IKeyboardActions
    {
        void OnCtrl(InputAction.CallbackContext context);
    }
}
